### ISSUE TITLE
D\Storybook\intro-storybook-angular-template-master\taskbox\node_modules\.bin\' is not recognized.

### ISSUE THREAD

**Issue by Prasanth-FrontEnd** [chromaui/intro-storybook-angular-template#5]
Followed the same steps in the given link: 

But facing an issue it is not recognized and cannot find module.

![IntroStorybookIssue](https://user-images.githubusercontent.com/83607976/144472673-d3dc5b40-bc02-400f-b1e0-21769cec2d3e.PNG)

Please give me a solution so that after testing I can apply this concept in my project.

**Comment by jonniebigodes** [comment]
Closing this as of now as the underlying issue is now fixed. It's not a template issue, but rather a Storybook issue.

Hope you understand.

Have a great week.

Stay safe
