### ISSUE TITLE
Unable to run storybook on M1 MacBook

### ISSUE THREAD

**Issue by ebh** [chromaui/intro-storybook-angular-template#6]
I'm following the [Storybook for Angular tutorial](https://storybook.js.org/tutorials/intro-to-storybook/angular/en/get-started/) on an M1 MacBook:

<img width="585" alt="image" src="https://user-images.githubusercontent.com/1782129/152099189-cdd10a62-aa77-45b0-bf0c-5928e6a7828a.png">

When attempt the `npm run storybook` step, I get this error:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1782129/152099377-7c05c51c-043f-4e54-b5f4-53cfef2d96aa.png">

Updating the version of `@compodoc/compodoc` in the `package.json` from `1.1.11` to `1.1.18` fixes the problem.

**Comment by ebh** [comment]
I've raised a Pull Request (#7) to "fix" the issue.

**Comment by jonniebigodes** [comment]
Closing this issue as fixed with #9 . Updated the template to use the new versions of Storybook and bumped it to Angular 13 and it seems to be working without any issues.

Feel free to reach out and I'll gladly re-open it if the issue surfaces back.
